---
apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprob
spec:
  containers:
    - name: app
      image: gcr.io/smartcity-gl/harmonic:v2.0.2
      ports:
        - name: http
          containerPort: 8000
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        initialDelaySeconds: 0
        periodSeconds: 2
        successThreshold: 1
        failureThreshold: 3